services:
  mysql-db-inventory:
    image: mariadb:10.6
    container_name: mysql-db-inventory
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: inventory-db
      MYSQL_USER: saad
      MYSQL_PASSWORD: kinan
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9999:80
    environment:
      PMA_HOST: mysql-db-inventory
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    restart: always
    depends_on:
      mysql-db-inventory:
        condition: service_healthy
    environment:
      - DB_URL=jdbc:mysql://mysql-db-inventory:3306/inventory-db
      - JWT_JWK_SET_URI=http://keycloak:8080/realms/customer-app-realm/protocol/openid-connect/certs
      - JWT_ISSUER_URI=http://keycloak:8080/realms/customer-app-realm
  postgres-service:
    image: postgres
    container_name: postgres-service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: saad
      POSTGRES_PASSWORD: kinan
    ports:
      - '5432:5432'
    expose:
      - '5432'
    healthcheck:
      test: "exit 0"
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: saad@gmail.com
      PGADMIN_DEFAULT_PASSWORD: kinan
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-service:5432/keycloak_db
      KC_DB_USERNAME: saad
      KC_DB_PASSWORD: kinan
      KEYCLOAK_ADMIN: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    restart: always
    ports:
      - '8080:8080'
    expose:
      - '8080'
    depends_on:
      - postgres-service
  customer-app:
    build: ./customer-app
    container_name: customer-app
    ports:
      - '8081:8081'
    expose:
      - '8081'
    restart: always
    depends_on:
      - keycloak
    environment:
      - KEYCLOAK_REDIRECT_URI=http://localhost:8081/login/oauth2/code/customer-app-client
      - KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/customer-app-realm
      - KEYCLOAK_AUTH_URI=http://localhost:8080/realms/customer-app-realm/protocol/openid-connect/auth
      - KEYCLOAK_TOKEN_URI=http://localhost:8080/realms/customer-app-realm/protocol/openid-connect/token
      - INVENTORY_SERVICE_BASE_URI=http://inventory-service:8082
  angular-front:
    build: ./angular-front-app
    container_name: angular-front
    ports:
      - '8083:80'
    expose:
      - '8083'
    restart: always
volumes:
  mysql_data:
  postgres_data:
  pgadmin_data: